spring:
  datasource:
    url: jdbc:postgresql://dec.coig.com:5432/poc
    username: venroll
    password: venroll
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9090