zuul:
  routes:
    persons:
      path: /people/**
      url: http://localhost:9090/persons
    first_person:
      path: /first/**
      url: http://localhost:9090/persons/get/1

server:
  port: 9091
ribbon:
  eureka:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
